### ISSUE TITLE
Error in the readme of the dataset camvid (inside the dataset folder of the cluster)

### ISSUE THREAD

**Issue by richardseba** [JoseLGomez/MCV_CNN_framework#3]
Hi, i was checking the readme of the camvid dataset to see how the mask was encoded inside of each groundtruth image, and the color_map that appears in the readme does not correspond with the real colormap used in the groundtruth.  It is not necesary to know this when using the framework but it is convinient to have if you want to analyze the distribution of classes of the dataset. 

Instead of:
```
color_map = {
        0: (128, 128, 128),    # sky
        1: (128, 0, 0),        # building
        2: (192, 192, 128),    # column_pole
        3: (128, 64, 128),     # road
        4: (0, 0, 192),        # sidewalk
        5: (128, 128, 0),      # Tree
        6: (192, 128, 128),    # SignSymbol
        7: (64, 64, 128),      # Fence
        8: (64, 0, 128),       # Car
        9: (64, 64, 0),        # Pedestrian
        10: (0, 128, 192),     # Bicyclist
        11: (0, 0, 0)          # Void
}
```

should be:
```
color_map = {
        0: (0, 0, 0),    # sky
        1: (1, 1, 1),        # building
        2: (2, 2, 2),    # column_pole
        3: (3, 3, 3),     # road
        4: (4, 4, 4),        # sidewalk
        5: (5, 5, 5),      # Tree
        6: (6, 6, 6),    # SignSymbol
        7: (7, 7, 7),      # Fence
        8: (8, 8, 8),       # Car
        9: (9, 9, 9),        # Pedestrian
        10: (10, 10, 10),     # Bicyclist
        11: (11, 11, 11)          # Void
}
```

I know this is not really part of the framework but I did not know where to ask about this problem.

**Comment by JoseLGomez** [comment]
Yes, this is not really a problem. We did on purpose in order to be able to visualize the output image of the segmentation with clear colors. If you use the original class values, you will see a black image basically, really difficult to evaluate qualitatively. Nevertheless you can do what you want to work comfortable with the framework.
